/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.server;



public class App {
    public static void main(String[] args) {
        System.out.println("Initializing Trivia Server...");
        
        // 1. Load Questions
        QuestionManager qm = new QuestionManager();
        System.out.println("Questions loaded: " + qm.getQuestions().size());
        
        // 2. Start Network
        ServerNetworkManager server = new ServerNetworkManager();
        server.startServer();
    }
}
